#!/bin/sh

CHANGED=$(git diff-index --name-only HEAD -- cloud-security/resources/ansible-roles/)
if [ -n "$CHANGED" ];
then
        echo "Ansible files have been updated so will create a new archive"
        git archive --output=cloud-security/resources/ansible-roles.tar.gz --format=tar.gz HEAD ./cloud-security/resources/ansible-roles/
        git add cloud-security/resources/ansible-roles.tar.gz
        exit 0
else
        echo "Ansible files have not updated"
        exit 0
fi
