---
- hosts: elk
  become: true
  roles:
  - role: elk

- hosts: webservers
  become: yes
  ignore_unreachable: true
  roles:
  - role: webservers
  - role: filebeat
  - role: metricbeat
  